version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "pub"
    directories:
      - "/"
    schedule:
      interval: "quarterly"
    versioning-strategy: increase-if-necessary
    groups:
      dart-dependencies:
        patterns:
          - "*"
